-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'SUPERADMIN');

-- CreateEnum
CREATE TYPE "Module" AS ENUM ('AUTH');

-- CreateEnum
CREATE TYPE "Acc" AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED');

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "firstname" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "othernames" STRING,
    "email" STRING NOT NULL,
    "phone" STRING,
    "emailverified" TIMESTAMP(3),
    "address" STRING,
    "role" "Role" NOT NULL DEFAULT 'USER',
    "permissions" STRING,
    "password" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),
    "status" "Acc" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Activity" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "activity" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "module" "Module" NOT NULL DEFAULT 'AUTH',

    CONSTRAINT "Activity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessiontoken" STRING NOT NULL,
    "userid" INT4 NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    "device" STRING,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" STRING NOT NULL,
    "token" STRING NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessiontoken_key" ON "Session"("sessiontoken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- AddForeignKey
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_userid_fkey" FOREIGN KEY ("userid") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userid_fkey" FOREIGN KEY ("userid") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
