-- AlterSequence
ALTER SEQUENCE "Department_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "Task" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING,
    "priority" STRING NOT NULL,
    "assignedto" STRING,
    "branch" STRING NOT NULL,
    "startdate" TIMESTAMP(3) NOT NULL,
    "enddate" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subtask" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "startdate" TIMESTAMP(3) NOT NULL,
    "enddate" TIMESTAMP(3) NOT NULL,
    "description" STRING,
    "createdby" STRING NOT NULL,
    "assignedto" STRING NOT NULL,

    CONSTRAINT "Subtask_pkey" PRIMARY KEY ("id")
);
