/*
  Warnings:

  - You are about to drop the `lastseen` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "lastseen";

-- CreateTable
CREATE TABLE "Lastseen" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lastseen_pkey" PRIMARY KEY ("id")
);
