-- AlterTable
ALTER TABLE "loanfee" ADD COLUMN     "chargerage" FLOAT8;

-- CreateTable
CREATE TABLE "collateral" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "documenttitle" STRING NOT NULL,
    "documentnumber" STRING NOT NULL,
    "description" STRING NOT NULL,
    "docposition" STRING NOT NULL DEFAULT 'ISSUED',
    "documentexpiration" TIMESTAMP(3),
    "worth" FLOAT8 NOT NULL,
    "file1" STRING,
    "file2" STRING,
    "file3" STRING,
    "file4" STRING,
    "file5" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "collateral_pkey" PRIMARY KEY ("id")
);
