/*
  Warnings:

  - Added the required column `accountnumber` to the `Accounts` table without a default value. This is not possible if the table is not empty.
  - Added the required column `createdby` to the `Accounts` table without a default value. This is not possible if the table is not empty.
  - Added the required column `dateadded` to the `Accounts` table without a default value. This is not possible if the table is not empty.

*/
-- AlterSequence
ALTER SEQUENCE "Supplier_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "savingsproduct_id_seq" MAXVALUE 9223372036854775807;

-- CreateEnum
CREATE TYPE "accounttype" AS ENUM ('ASSET', 'CASH', 'CURRENT_ASSETS', 'EXPENSE', 'INCOME', 'EQUITY_RETAINED_EARNINGS', 'EQUITY_DOES_NOT_CLOSE', 'INVENTORY', 'OTHER_ASSET', 'COST_OF_SALES', 'FIXED_ASSET', 'OTHER_CURRENT_ASSET', 'ACCOUNTS_PAYABLE', 'ACCOUNTS_RECEIVABLE', 'ACCUMULATED_DEPRECIATION', 'LIABILITIES', 'OTHER_CURRENT_LIABILITIES', 'LONG_TERM_LIABILITIES', 'EQUITY');

-- AlterTable
ALTER TABLE "Accounts" ADD COLUMN     "accountnumber" STRING NOT NULL;
ALTER TABLE "Accounts" ADD COLUMN     "accounttype" STRING;
ALTER TABLE "Accounts" ADD COLUMN     "createdby" INT4 NOT NULL;
ALTER TABLE "Accounts" ADD COLUMN     "dateadded" TIMESTAMP(3) NOT NULL;
ALTER TABLE "Accounts" ADD COLUMN     "description" STRING;
ALTER TABLE "Accounts" ADD COLUMN     "groupname" STRING;
ALTER TABLE "Accounts" ADD COLUMN     "status" STRING NOT NULL DEFAULT 'ACTIVE';

-- CreateTable
CREATE TABLE "savings" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "accountnumber" INT4 NOT NULL,
    "personnel" INT4 NOT NULL,
    "amount" INT4 NOT NULL,
    "branch" INT4 NOT NULL,
    "registrationpoint" INT4 NOT NULL,
    "registrationcharge" INT4 NOT NULL,
    "registrationdate" TIMESTAMP(3) NOT NULL,
    "registrationdesc" STRING,
    "bankname1" STRING,
    "accountname1" INT4,
    "bankname2" STRING,
    "accountname2" INT4,
    "accountofficer" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "savings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "personnel" INT4 NOT NULL,
    "amount" INT4 NOT NULL,
    "oldamount" INT4,
    "branch" INT4 NOT NULL,
    "registrationpoint" INT4 NOT NULL,
    "registrationcharge" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "updateddated" TIMESTAMP(3),
    "updatedby" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "transaction_pkey" PRIMARY KEY ("id")
);
