/*
  Warnings:

  - You are about to drop the column `referral` on the `User` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Branch" ADD COLUMN     "createdby" INT4 NOT NULL DEFAULT 0;
ALTER TABLE "Branch" ADD COLUMN     "lastupdated" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "User" DROP COLUMN "referral";
ALTER TABLE "User" ADD COLUMN     "createdby" INT4 NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "Member" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "Acc" NOT NULL DEFAULT 'ACTIVE',
    "lastupdated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Member_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" INT4 NOT NULL DEFAULT 1,
    "userid" INT4 NOT NULL,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Position" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "position" STRING NOT NULL,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),

    CONSTRAINT "Position_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Member_member_key" ON "Member"("member");

-- CreateIndex
CREATE UNIQUE INDEX "Position_position_key" ON "Position"("position");
