/*
  Warnings:

  - You are about to drop the `Member` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Member";

-- CreateTable
CREATE TABLE "Department" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "department" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "userid" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "Acc" NOT NULL DEFAULT 'ACTIVE',
    "lastupdated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Department_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DefineMember" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "Acc" NOT NULL DEFAULT 'ACTIVE',
    "lastupdated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "DefineMember_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "DefineMember_member_key" ON "DefineMember"("member");
