-- AlterSequence
ALTER SEQUENCE "Cashierlimit_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "Inventory_id_seq" MAXVALUE 9223372036854775807;

-- AlterEnum
ALTER TYPE "Acc" ADD VALUE 'PENDING';

-- AlterTable
ALTER TABLE "Inventory" ADD COLUMN     "issue" STRING;
ALTER TABLE "Inventory" ADD COLUMN     "issuetype" STRING;
ALTER TABLE "Inventory" ADD COLUMN     "supplier" STRING;

-- CreateTable
CREATE TABLE "issue" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "issuetype" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "issue_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "issue_issuetype_key" ON "issue"("issuetype");
