-- AlterSequence
ALTER SEQUENCE "Accounts_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "Subtask_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "Inventory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "itemid" INT4 NOT NULL,
    "itemname" STRING NOT NULL,
    "department" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "units" STRING NOT NULL,
    "cost" INT4 NOT NULL,
    "price" INT4 NOT NULL,
    "pricetwo" INT4 NOT NULL,
    "beginbalance" INT4 NOT NULL,
    "qty" INT4 NOT NULL,
    "minimumbalance" INT4 NOT NULL,
    "group" STRING,
    "applyto" STRING NOT NULL,
    "itemclass" STRING NOT NULL,
    "composite" STRING NOT NULL,
    "compositeid" INT4 NOT NULL,
    "description" STRING,
    "imageone" STRING,
    "imagetwo" STRING,
    "imagethree" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" INT4 NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Inventory_pkey" PRIMARY KEY ("id")
);
