-- AlterTable
ALTER TABLE "User" ADD COLUMN     "registrationpoint" INT4 NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "Rejecttransactiondate" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rejectiondate" TIMESTAMP(3) NOT NULL,
    "branch" INT4,
    "reason" STRING,

    CONSTRAINT "Rejecttransactiondate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Registrationpoint" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "registrationpoint" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "datecreated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Registrationpoint_pkey" PRIMARY KEY ("id")
);
