-- CreateTable
CREATE TABLE "frequencyoverride" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "compulsorydepositfrequency" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "frequencyoverride_pkey" PRIMARY KEY ("id")
);
