-- CreateTable
CREATE TABLE "lastseen" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "lastseen_pkey" PRIMARY KEY ("id")
);
