-- AlterSequence
ALTER SEQUENCE "Interest_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "savings_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "transaction_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "loanfee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "feename" STRING NOT NULL,
    "feemethod" STRING NOT NULL,
    "chargesbasedon" STRING NOT NULL,
    "glaccount" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "loanfee_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "loanfee_feename_key" ON "loanfee"("feename");
