-- AlterSequence
ALTER SEQUENCE "Lastseen_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "loanproduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "productname" STRING NOT NULL,
    "description" STRING,
    "registrationcharge" FLOAT8,
    "repaymentsettings" STRING NOT NULL,
    "repaymentfrequency" STRING,
    "numberofrepayments" INT4,
    "duration" INT4,
    "durationcategory" STRING,
    "interestmethod" STRING NOT NULL,
    "interestrate" FLOAT8 NOT NULL,
    "defaultpenaltyid" INT4,
    "currency" STRING,
    "excludebranch" STRING,
    "productofficer" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "loanproduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loanaccounts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "loanaccount" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "registrationpoint" INT4,
    "registrationcharge" FLOAT8,
    "registrationdate" TIMESTAMP(3) NOT NULL,
    "registrationdesc" STRING,
    "bankname1" STRING,
    "bankaccountname1" STRING,
    "bankaccountnumber1" INT4,
    "bankname2" STRING,
    "bankaccountname2" STRING,
    "bankaccountnumber2" STRING,
    "accountofficer" STRING,
    "repaymentfrequency" STRING,
    "numberofrepayments" INT4,
    "duration" INT4,
    "durationcategory" STRING,
    "interestmethod" STRING NOT NULL,
    "interestrate" FLOAT8 NOT NULL,
    "defaultpenaltyid" INT4,

    CONSTRAINT "loanaccounts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "loanproduct_productname_key" ON "loanproduct"("productname");
