-- CreateTable
CREATE TABLE "savingsproduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "productname" STRING NOT NULL,
    "currency" STRING NOT NULL,
    "allowdeposit" BOOL NOT NULL,
    "allowwithdrawal" BOOL NOT NULL,
    "withdrawallimit" FLOAT8 NOT NULL,
    "withdrawalcharges" FLOAT8 NOT NULL,
    "withdrawalchargetype" STRING NOT NULL,
    "withdrawalchargeinterval" STRING NOT NULL,
    "depositcharge" FLOAT8 NOT NULL,
    "withdrawallimittype" STRING NOT NULL,
    "activationfee" FLOAT8 NOT NULL,
    "minimumaccountbalance" FLOAT8 NOT NULL,
    "allowoverdrawn" BOOL NOT NULL,
    "compulsorydeposit" BOOL NOT NULL,
    "compulsorydeposittype" STRING NOT NULL,
    "compulsorydepositspillover" BOOL NOT NULL,
    "compulsorydepositfrequency" STRING NOT NULL,
    "compulsorydepositfrequencyamount" INT4 NOT NULL,
    "compulsorydepositfrequencyskip" INT4 NOT NULL,
    "compulsorydepositpenalty" FLOAT8 NOT NULL,
    "compulsorydepositpenaltytype" STRING NOT NULL,
    "compulsorydepositpenaltyfrom" STRING NOT NULL,
    "compulsorydepositpenaltyfallbackfrom" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "savingsproduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Interest" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductId" INT4 NOT NULL,
    "interestname" STRING NOT NULL,
    "interestmethod" STRING NOT NULL,
    "eligibilityaccountage" INT4 NOT NULL,
    "eligibilitybalance" FLOAT8 NOT NULL,
    "interestamount" FLOAT8 NOT NULL,
    "interesttype" STRING NOT NULL,
    "interestfrequency" STRING NOT NULL,
    "interestfrequencynumber" INT4 NOT NULL,
    "interestfrequencyskip" INT4 NOT NULL,
    "goforapproval" BOOL NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Interest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Deduction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductId" INT4 NOT NULL,
    "deductionname" STRING NOT NULL,
    "eligibilityaccountage" INT4 NOT NULL,
    "eligibilitybalance" FLOAT8 NOT NULL,
    "deductionamount" FLOAT8 NOT NULL,
    "deductiontype" STRING NOT NULL,
    "deductionmethod" STRING NOT NULL,
    "deductionfrequency" STRING NOT NULL,
    "deductionfrequencynumber" INT4 NOT NULL,
    "deductionfrequencyskip" INT4 NOT NULL,
    "goforapproval" BOOL NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Deduction_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Interest" ADD CONSTRAINT "Interest_savingsproductId_fkey" FOREIGN KEY ("savingsproductId") REFERENCES "savingsproduct"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Deduction" ADD CONSTRAINT "Deduction_savingsproductId_fkey" FOREIGN KEY ("savingsproductId") REFERENCES "savingsproduct"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
