-- CreateTable
CREATE TABLE "loanpaymentschedule" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "scheduledpaymentdate" TIMESTAMP(3) NOT NULL,
    "gracepaymentdate" TIMESTAMP(3),
    "scheduleamount" FLOAT8 NOT NULL,
    "interestamount" FLOAT8 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdby" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "loanpaymentschedule_pkey" PRIMARY KEY ("id")
);
