-- AlterSequence
ALTER SEQUENCE "Activity_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "Session_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "branch" INT4 NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN     "country" STRING;
ALTER TABLE "User" ADD COLUMN     "state" STRING;

-- CreateTable
CREATE TABLE "Branch" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "branch" INT4 NOT NULL,
    "country" STRING,
    "state" STRING,
    "address" STRING,
    "status" "Acc" NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);
