-- AlterSequence
ALTER SEQUENCE "Rejecttransactiondate_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "Task_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "Subtask" ADD COLUMN     "taskstatus" STRING NOT NULL DEFAULT 'NOT STARTED';

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "taskstatus" STRING NOT NULL DEFAULT 'NOT STARTED';

-- CreateTable
CREATE TABLE "Cashierlimit" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cashier" INT4 NOT NULL,
    "depositlimit" INT4 NOT NULL,
    "withdrawallimit" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" INT4 NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Cashierlimit_pkey" PRIMARY KEY ("id")
);
